#!modules/module.sh

help="
$(gettext "Print current date and verify that NTP can synchronize time.")
"

run () {
	section "Current time"
	date

	section "UCI configuration"
	subsection "NTP configuration"
	uci -q show 'system.ntp' || error 'Can not get ntp configuration'

	section "NTPd"
	subsection "Is /etc/init.d/sysntpd enabled?"
	md5sum /etc/init.d/*sysntpd* /etc/rc.d/*sysntpd*

	subsection "Restart /etc/init.d/sysntpd to force sync"
	/etc/init.d/sysntpd restart && echo "OK"

	section "Current time after sync"
	date
}

# vim: ft=sh
