#!modules/module.sh

help="
$(gettext "List all mount points and mount options and all block devices including amount of free space.")
"

run () {
	section "Mountpoints"
	mount

	section "Block devices"
	lsblk -O

	section "Filesystem disk space usage"
	df -h

	section "File space usage of /tmp"
	du -ahcx /tmp/

	if check_installed smartctl; then
		section "S.M.A.R.T."
		for drive in /dev/sd* /dev/nvme*; do
			[ -e "$drive" ] || continue
			subsection "$drive"
			smartctl -a "$drive"
		done
	fi
}

# vim: ft=sh
