#!modules/module.sh

help="
$(gettext "List installed packages and OPKG configuration.")
"

run() {
	section "Installed packages"
	opkg list-installed

	section "OPKG feeds update"
	opkg update

	section "OPKG configuration"
	dump_file "/etc/opkg/distfeeds.conf"
	dump_file "/etc/opkg/customfeeds.conf"

	section "OPKG file consistency check"
	pkg_check

	# Note: these are public keys so they are public and there is no issue in
	# including them as they are.
	section "OPKG public keys"
	dump_file /etc/opkg/keys/*

	section "Updater's public keys"
	dump_file /etc/updater/keys/*.pub

	section "Updater UCI config"
	dump_file '/etc/config/updater'

	section "Package lists UCI config"
	dump_file '/etc/config/pkglists'

	section "Updater configuration"
	local updater_confdir='/etc/updater/conf.d'
	local updater_conffile
	if [ -d "$updater_confdir" ]; then
		find "$updater_confdir" -type f -name '*.lua' \
			| while read -r updater_conffile; do
				dump_file "$updater_conffile"
			done
	else
		error "There is no '$updater_confdir' directory"
	fi

	section "Updater execution"
	pkgupdate -e TRACE
}

# vim: ft=sh
