#!modules/module.sh

help="
$(gettext "Print current date and verify that NTP can synchronize time.")
"

run () {
	section "Current time"
	date

	section "NTP configuration"
	uci show system.ntp

	section "Is /etc/init.d/sysntpd enabled?"
	find /etc/init.d/*sysntpd* -exec md5sum {} \;
	find /etc/rc.d/*sysntpd* -exec md5sum {} \;

	section "/etc/init.d/sysntpd restart to force sync"
	/etc/init.d/sysntpd restart

	section "Current time after sync"
	date
}

# vim: ft=sh
