#!modules/module.sh

help="
$(gettext "Gather DNS related information.")
"

resolve() {
	echo "Attempting to resolve $1"
	dig @127.0.0.1 +dnssec "$1"
}

run () {
	local rootkeyfile resolver kresd_tty

	section "Resolver config"
	uci -q show resolver

	section "resolv.conf*"
	grep -H '' /etc/resolv.conf* /tmp/resolv.conf*

	section "DNSSEC root key file"
	rootkeyfile=$(uci get resolver.common.keyfile)
	ls -al "$rootkeyfile"
	md5sum "$rootkeyfile"
	grep -H '' "$rootkeyfile"
	echo

	section "Resolver process"
	resolver="$(uci get resolver.common.prefered_resolver)"
	ps w | grep "$resolver"

	if [ "$resolver" == "kresd" ]; then
		section "Configured trust anchors"
		kresd_tty="$(uci get resolver.kresd.rundir)/tty/$(pidof kresd)"
		echo "trust_anchors" | socat - "unix-connect:${kresd_tty}"
	fi

	section "Resolution attempts"
	resolve api.turris.cz  # should pass
	resolve www.google.com  # should pass
	resolve www.facebook.com  # should pass
	resolve www.youtube.com  # should pass

	resolve www.rhybar.cz  # should fail
	resolve *.wilda.rhybar.0skar.cz  # should fail
	resolve *.wilda.nsec.0skar.cz  # should pass
	resolve *.wild.nsec.0skar.cz  # should pass
	resolve *.wilda.0skar.cz  # should pass
	resolve *.wild.0skar.cz  # should pass
	resolve www.wilda.nsec.0skar.cz  # should pass
	resolve www.wilda.0skar.cz  # should pass
	resolve *.wilda.rhybar.ecdsa.0skar.cz  # should fail
}

# vim: ft=sh
