#!modules/module.sh

help="
$(gettext "Gather DNS related information.")
"

resolve() {
	echo "Attempting to resolve $1"
	dig @127.0.0.1 +dnssec "$1"
}

run () {
	section "Resolver config"
	uci -q show resolver

	section "resolv.conf*"
	grep -H '' /etc/resolv.conf* /tmp/resolv.conf*

	section "DNSSEC root key file"
	ROOTKEYFILE=$(uci get resolver.common.keyfile)
	ls -al "${ROOTKEYFILE}"
	md5sum "${ROOTKEYFILE}"
	grep -H '' "${ROOTKEYFILE}"
	echo

	section "Resolver process"
	RESOLVER="$(uci get resolver.common.prefered_resolver)"
	ps w | grep ${RESOLVER}

	if [ "${RESOLVER}" == "kresd" ]; then
		section "Configured trust anchors"
		KRESD_TTY="$(uci get resolver.kresd.rundir)/tty/$(pidof kresd)"
		echo "trust_anchors" | socat - "unix-connect:${KRESD_TTY}"
	fi

	section "Resolution attempts"
	resolve api.turris.cz  # should pass
	resolve www.google.com  # should pass
	resolve www.facebook.com  # should pass
	resolve www.youtube.com  # should pass

	resolve www.rhybar.cz  # should fail
	resolve *.wilda.rhybar.0skar.cz  # should fail
	resolve *.wilda.nsec.0skar.cz  # should pass
	resolve *.wild.nsec.0skar.cz  # should pass
	resolve *.wilda.0skar.cz  # should pass
	resolve *.wild.0skar.cz  # should pass
	resolve www.wilda.nsec.0skar.cz  # should pass
	resolve www.wilda.0skar.cz  # should pass
	resolve *.wilda.rhybar.ecdsa.0skar.cz  # should fail
}

# vim: ft=sh
