#!modules/module.sh

help="
$(gettext "Current and factory /etc/os-release file (/etc/turris-version for factory as well).")
"

version_btrfs() {
	local device="$1"
	local mnt="$(mktemp -d)"
	mount -t btrfs -o ro,subvol=@factory "$device" "$mnt"
	cat "$mnt/etc/turris-version"
	cat "$mnt/etc/os-release"
	umount "$mnt"
	rmdir "$mnt"
}

version_1x() {
	local mnt="$(mktemp -d)"
	mount -t squashfs /dev/mtdblock3 "$mnt"
	tar -xJf "$mnt/medkit.tar.xz" ./etc/turris-version ./etc/os-release -O
	umount "$mnt"
	rmdir "$mnt"
}

run () {
	echo_sec "Current"
	cat /etc/os-release

	echo_sec "Factory"
	(
	. /etc/os-release
	case "$LEDE_DEVICE_PRODUCT" in
		"Turris 1.x")
			version_1x
			;;
		"Turris Omnia")
			version_btrfs /dev/mmcblk0p1
			;;
		"Turris Mox")
			version_btrfs /dev/mmcblk1p1
			;;
		*)
			echo "Can't identify Turris model!"
			;;
	esac
	)
}

# vim: ft=sh
