#!modules/module.sh

help="
try to run updater, read /tmp/updater_crash.log and dump configuration
"

run () {
	echo_sec "Updater execution"
	pkgupdate -e TRACE
	echo
	local CRASH_LOG="/tmp/updater_crash.log"
	if [ -e "$CRASH_LOG" ]; then
		cat "$CRASH_LOG"
	else
		echo "No updater crashlog file ($CRASH_LOG)"
	fi

	echo_sec "Updater configuration"
	if [ -d /etc/updater/conf.d ]; then
		for F in $(find /etc/updater/conf.d -type f -name *.lua); do
			echo "## $F ##"
			cat "$F"
		done
	else
		echo "No /etc/updater/conf.d directory"
	fi
}
